name: flutter_application_01
description: "pokemon project."
publish_to: 'none'
package_rename_config:
  android:
    app_name: 'Pokemon Android'
  ios:
    app_name: 'Pokemon iOS'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^9.2.2
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  animate_do: ^2.1.0
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.17
  state_notifier: ^0.7.2+1
  firebase_core:
  firebase_storage:
  cloud_firestore:
  rename:
  rename_app:
  package_rename_plus: ^1.0.1
  floating_snackbar:
  google_sign_in:
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  flutter_osm_plugin: ^1.3.3+1
  latlong2: ^0.9.0
  http: ^1.2.2
  pointer_interceptor:
  geocoding:
  url_launcher: ^6.3.1
  introduction_screen: ^3.1.14

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  state_notifier_test: ^0.0.9
  test_coverage_badge: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/illustration/